const contractTokens = [
	"--font-display",
	"--font-heading",
	"--font-body",
	"--font-mono",
	"--heading-transform",
	"--heading-tracking",
	"--text-2xl",
	"--text-3xl",
	"--text-4xl",
	"--border-width",
	"--border-width-thick",
	"--color-text",
	"--color-text-muted",
	"--color-background",
	"--color-surface",
	"--color-border",
	"--color-border-hover",
	"--color-border-interactive",
	"--color-primary",
	"--color-primary-hover",
	"--color-primary-focus",
	"--color-button-primary-bg",
	"--color-button-primary-bg-hover",
	"--color-button-primary-text",
	"--radius-sm",
	"--radius-md",
	"--radius-lg",
	"--radius-full",
	"--shadow-sm",
	"--shadow-md",
	"--shadow-lg",
	"--duration-fast",
	"--duration-normal",
	"--duration-slow",
];

export default contractTokens;
